/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import entites.Createur;
import entites.Editeur;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author BTS sio
 */
public class JFrameBase extends javax.swing.JFrame {
    public App app;   //Attribut pour lier avec App.java
    public ArrayList<String> listeAttributsOuvrage;
    private int idCreateur = -1;
    private int idEditeur = -1;
    private String id = "0";
    private String titre = "titre ouvrage";

    /**
     * Creates new form JFrameBase
     * @param appIn
     */
    public JFrameBase(App appIn) {
        app = appIn;
        initComponents();
        init();
    }
    
    public JFrameBase() {
        initComponents();
    }
    
    /*
    * Initialisation des formulaires
    * Insère les listes de choixs possibles dans les tableaux de saisie 
    */
    private void init() {
       ArrayList[] listeCles = this.app.listeClesEtrangeres;        
        // Types d'ouvrages
        TableColumn colTypeOuv = jTableOuvrage.getColumnModel().getColumn(1);
        JComboBox comboBox = new JComboBox();
        for (int i=1; i < listeCles[0].size(); i += 2) {
            comboBox.addItem(listeCles[0].get(i));
        }
        colTypeOuv.setCellEditor(new DefaultCellEditor(comboBox));
        
        // langue
        TableColumn colLangue = jTableOuvrage.getColumnModel().getColumn(8);
        JComboBox comboBoxL = new JComboBox();
        for (int i=1; i < listeCles[1].size(); i += 2) {
            comboBoxL.addItem(listeCles[1].get(i));
        }
        colLangue.setCellEditor(new DefaultCellEditor(comboBoxL));
        
        // Stock
        TableColumn colStock = jTableMeta.getColumnModel().getColumn(0);
        JComboBox comboBoxM = new JComboBox();
        for (int i=1; i < listeCles[2].size(); i += 2) {
            comboBoxM.addItem(listeCles[2].get(i));
        }
        colStock.setCellEditor(new DefaultCellEditor(comboBoxM));
        
        // Catégorie
        TableColumn colCateg = jTableMeta.getColumnModel().getColumn(1);
        JComboBox comboBoxCateg = new JComboBox();
        for (int i=1; i < listeCles[3].size(); i += 2) {
            comboBoxCateg.addItem(listeCles[3].get(i));
        }
        colCateg.setCellEditor(new DefaultCellEditor(comboBoxCateg));
        
        // Univers
        TableColumn colUniv = jTableMeta.getColumnModel().getColumn(2);
        JComboBox comboBoxUniv = new JComboBox();
        for (int i=1; i < listeCles[4].size(); i += 2) {
            comboBoxUniv.addItem(listeCles[4].get(i));
        }
        colUniv.setCellEditor(new DefaultCellEditor(comboBoxUniv));
       
        // Créateur
        TableColumn comboboxCreateur = jTableCreateur.getColumnModel().getColumn(3);
        JComboBox comboBoxC = new JComboBox();
        for (int i=1; i < listeCles[5].size(); i += 2) {
            comboBoxC.addItem(listeCles[5].get(i));
        }
        comboboxCreateur.setCellEditor(new DefaultCellEditor(comboBoxC));
         
        // Editeur
        TableColumn comboboxEditeur = jTableEditeur.getColumnModel().getColumn(2);
        JComboBox comboBoxE = new JComboBox();
        for (int i=1; i < listeCles[6].size(); i += 2) {
            comboBoxE.addItem(listeCles[6].get(i));
        }
        comboboxEditeur.setCellEditor(new DefaultCellEditor(comboBoxE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCreateur = new javax.swing.JDialog();
        jLabeConfirmer = new javax.swing.JLabel();
        jComboBoxConfirmer = new javax.swing.JComboBox<>();
        jButtonConfirmer = new javax.swing.JButton();
        jLabelAjoutCreateur = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCreateur = new javax.swing.JTable();
        jButtonAjoutCreateur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDialogEditeur = new javax.swing.JDialog();
        jLabeConfirmerE = new javax.swing.JLabel();
        jComboBoxConfirmerE = new javax.swing.JComboBox<>();
        jButtonConfirmerE = new javax.swing.JButton();
        jLabelAjoutEditeur = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableEditeur = new javax.swing.JTable();
        jButtonAjoutEditeur = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        contenant = new javax.swing.JPanel();
        bandeau = new javax.swing.JPanel();
        bureau = new javax.swing.JPanel();
        jPanelAcceuil = new javax.swing.JPanel();
        jLabelTitreAcceuil = new javax.swing.JLabel();
        jPanelRechercher = new javax.swing.JPanel();
        jLabelTitreRechercher = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRes = new javax.swing.JTable();
        jLabelTrouver = new javax.swing.JLabel();
        jLabelTrouverDans = new javax.swing.JLabel();
        jComboBoxTrouverChamps = new javax.swing.JComboBox<>();
        jButtonRechercher = new javax.swing.JButton();
        jTextFieldRecherche = new javax.swing.JTextField();
        jLabelResultats = new javax.swing.JLabel();
        jLabelRien = new javax.swing.JLabel();
        jPanelCatalogue = new javax.swing.JPanel();
        jLabelTitreCatalogue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCatalogue = new javax.swing.JTable();
        jPanelMaJ = new javax.swing.JPanel();
        jLabelTitreMaJ = new javax.swing.JLabel();
        jLabelInfoOuvrage = new javax.swing.JLabel();
        jButtonSoumetAjout = new javax.swing.JButton();
        jScrollPaneOuvrage = new javax.swing.JScrollPane();
        jTableOuvrage = new javax.swing.JTable();
        jLabelInfoMedia = new javax.swing.JLabel();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonAnnuler.setVisible(false);
        jScrollPaneMeta = new javax.swing.JScrollPane();
        jTableMeta = new javax.swing.JTable();
        jLabelAjouter = new javax.swing.JLabel();
        jButtonEnvoyerAjout = new javax.swing.JButton();
        jButtonEnvoyerAjout.setVisible(false);
        jPanelSuppression = new javax.swing.JPanel();
        jLabelOuvrageSuppresion = new javax.swing.JLabel();
        jTextFieldSupression = new javax.swing.JTextField();
        jLabelTitreSupression = new javax.swing.JLabel();
        jButtonSuppression = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSupprimer = new javax.swing.JTable();
        jPanelEmprunt = new javax.swing.JPanel();
        jLabelTitreEmprunt = new javax.swing.JLabel();
        jScrollPaneEmpruntEnCours = new javax.swing.JScrollPane();
        jTableEmprunts = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuCatalogue = new javax.swing.JMenu();
        jMenuVoir = new javax.swing.JMenuItem();
        menuRechercher = new javax.swing.JMenu();
        jMenuRecherche = new javax.swing.JMenuItem();
        menuMaJ = new javax.swing.JMenu();
        jMenuAjout = new javax.swing.JMenuItem();
        jMenuSuppression = new javax.swing.JMenuItem();
        MenuEmprunt = new javax.swing.JMenu();
        jMenuAfficheEmprunts = new javax.swing.JMenuItem();

        jDialogCreateur.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogCreateur.setBackground(new java.awt.Color(255, 204, 153));
        jDialogCreateur.setLocation(new java.awt.Point(60, 60));
        jDialogCreateur.setMinimumSize(new java.awt.Dimension(800, 500));
        jDialogCreateur.setModal(true);

        jLabeConfirmer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeConfirmer.setText("Confirmer un créateur existant");

        jButtonConfirmer.setText("Confirmer");
        jButtonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmerActionPerformed(evt);
            }
        });

        jLabelAjoutCreateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAjoutCreateur.setText("Ajouter un nouveau créateur");

        jTableCreateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Naissance", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCreateur.setColumnSelectionAllowed(true);
        jScrollPane5.setViewportView(jTableCreateur);

        jButtonAjoutCreateur.setText("Ajouter");
        jButtonAjoutCreateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutCreateurActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("OU");

        javax.swing.GroupLayout jDialogCreateurLayout = new javax.swing.GroupLayout(jDialogCreateur.getContentPane());
        jDialogCreateur.getContentPane().setLayout(jDialogCreateurLayout);
        jDialogCreateurLayout.setHorizontalGroup(
            jDialogCreateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCreateurLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialogCreateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxConfirmer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jDialogCreateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAjoutCreateur)
                    .addComponent(jButtonConfirmer))
                .addGap(44, 44, 44))
            .addGroup(jDialogCreateurLayout.createSequentialGroup()
                .addGroup(jDialogCreateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCreateurLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabeConfirmer))
                    .addGroup(jDialogCreateurLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabelAjoutCreateur))
                    .addGroup(jDialogCreateurLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogCreateurLayout.setVerticalGroup(
            jDialogCreateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCreateurLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabeConfirmer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogCreateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmer))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelAjoutCreateur)
                .addGroup(jDialogCreateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCreateurLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonAjoutCreateur))
                    .addGroup(jDialogCreateurLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jDialogEditeur.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogEditeur.setLocation(new java.awt.Point(60, 60));
        jDialogEditeur.setMinimumSize(new java.awt.Dimension(800, 500));
        jDialogEditeur.setModal(true);

        jLabeConfirmerE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeConfirmerE.setText("Confirmer un éditeur existant");

        jButtonConfirmerE.setText("Confirmer");
        jButtonConfirmerE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmerEActionPerformed(evt);
            }
        });

        jLabelAjoutEditeur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAjoutEditeur.setText("Ajouter un nouvel éditeur");

        jTableEditeur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nom", "Ville", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableEditeur);

        jButtonAjoutEditeur.setText("Ajouter");
        jButtonAjoutEditeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutEditeurActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("OU");
        jLabel2.setAlignmentX(20.0F);
        jLabel2.setAlignmentY(20.0F);

        javax.swing.GroupLayout jDialogEditeurLayout = new javax.swing.GroupLayout(jDialogEditeur.getContentPane());
        jDialogEditeur.getContentPane().setLayout(jDialogEditeurLayout);
        jDialogEditeurLayout.setHorizontalGroup(
            jDialogEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEditeurLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAjoutEditeur)
                .addGap(177, 177, 177))
            .addGroup(jDialogEditeurLayout.createSequentialGroup()
                .addGroup(jDialogEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditeurLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabeConfirmerE))
                    .addGroup(jDialogEditeurLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jDialogEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxConfirmerE, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jDialogEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAjoutEditeur)
                            .addComponent(jButtonConfirmerE)))
                    .addGroup(jDialogEditeurLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jDialogEditeurLayout.setVerticalGroup(
            jDialogEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditeurLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabeConfirmerE)
                .addGap(18, 18, 18)
                .addGroup(jDialogEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmerE)
                    .addComponent(jComboBoxConfirmerE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(jLabelAjoutEditeur)
                .addGap(33, 33, 33)
                .addGroup(jDialogEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjoutEditeur))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));

        contenant.setLayout(new java.awt.BorderLayout());

        bandeau.setMinimumSize(new java.awt.Dimension(100, 50));
        bandeau.setPreferredSize(new java.awt.Dimension(992, 50));

        javax.swing.GroupLayout bandeauLayout = new javax.swing.GroupLayout(bandeau);
        bandeau.setLayout(bandeauLayout);
        bandeauLayout.setHorizontalGroup(
            bandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        bandeauLayout.setVerticalGroup(
            bandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        contenant.add(bandeau, java.awt.BorderLayout.PAGE_START);

        bureau.setLayout(new java.awt.CardLayout());

        jLabelTitreAcceuil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitreAcceuil.setText("Bienvenue");

        javax.swing.GroupLayout jPanelAcceuilLayout = new javax.swing.GroupLayout(jPanelAcceuil);
        jPanelAcceuil.setLayout(jPanelAcceuilLayout);
        jPanelAcceuilLayout.setHorizontalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabelTitreAcceuil)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        jPanelAcceuilLayout.setVerticalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreAcceuil)
                .addContainerGap(703, Short.MAX_VALUE))
        );

        bureau.add(jPanelAcceuil, "card2");

        jLabelTitreRechercher.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitreRechercher.setText("Rechercher");

        jTableRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Titre", "Nom", "Prénom", "Editeur", "Année", "Pages", "Langue", "Catégorie", "Univers", "Format", "Identifiant", "Cote"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRes.setRowHeight(20);
        jTableRes.setShowGrid(true);
        jTableRes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableResAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTableRes);

        jLabelTrouver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrouver.setText("Trouver ce texte");

        jLabelTrouverDans.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrouverDans.setText("dans le champ");

        jComboBoxTrouverChamps.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxTrouverChamps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir champ", "Tous", "Titre", "Auteur", "Identifiant" }));
        jComboBoxTrouverChamps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrouverChampsActionPerformed(evt);
            }
        });

        jButtonRechercher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonRechercher.setText("Lancer la recherche");
        jButtonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercherActionPerformed(evt);
            }
        });

        jTextFieldRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRechercheActionPerformed(evt);
            }
        });

        jLabelResultats.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResultats.setText("Résultats");

        jLabelRien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRien.setForeground(new java.awt.Color(255, 51, 51));
        jLabelRien.setText("Ancun résultat");

        javax.swing.GroupLayout jPanelRechercherLayout = new javax.swing.GroupLayout(jPanelRechercher);
        jPanelRechercher.setLayout(jPanelRechercherLayout);
        jPanelRechercherLayout.setHorizontalGroup(
            jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechercherLayout.createSequentialGroup()
                .addGroup(jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRechercherLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabelTitreRechercher))
                    .addGroup(jPanelRechercherLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRechercherLayout.createSequentialGroup()
                                .addGroup(jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTrouver)
                                    .addComponent(jLabelResultats))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRechercherLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelRien, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRechercherLayout.createSequentialGroup()
                                        .addComponent(jTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabelTrouverDans)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxTrouverChamps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jButtonRechercher)))))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanelRechercherLayout.setVerticalGroup(
            jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechercherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreRechercher)
                .addGap(162, 162, 162)
                .addGroup(jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrouver)
                    .addComponent(jTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrouverDans)
                    .addComponent(jComboBoxTrouverChamps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRechercher))
                .addGap(13, 13, 13)
                .addGroup(jPanelRechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResultats)
                    .addComponent(jLabelRien))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        jLabelRien.setVisible(false);

        bureau.add(jPanelRechercher, "card2");

        jLabelTitreCatalogue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitreCatalogue.setText("Catalogue");

        jTableCatalogue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titre", "Auteur", "Type", "Editeur", "Année", "Pages", "Langue", "Catégorie", "Univers", "Format", "Identifiant", "Cote"
            }
        ));
        jScrollPane1.setViewportView(jTableCatalogue);

        javax.swing.GroupLayout jPanelCatalogueLayout = new javax.swing.GroupLayout(jPanelCatalogue);
        jPanelCatalogue.setLayout(jPanelCatalogueLayout);
        jPanelCatalogueLayout.setHorizontalGroup(
            jPanelCatalogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCatalogueLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabelTitreCatalogue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCatalogueLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCatalogueLayout.setVerticalGroup(
            jPanelCatalogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCatalogueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreCatalogue)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );

        bureau.add(jPanelCatalogue, "card2");

        jLabelTitreMaJ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitreMaJ.setText("Mise à jour du catalogue");

        jLabelInfoOuvrage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInfoOuvrage.setText("Détails de l'ouvrage");

        jButtonSoumetAjout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSoumetAjout.setText("Soumettre");
        jButtonSoumetAjout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSoumetAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSoumetAjoutActionPerformed(evt);
            }
        });

        jTableOuvrage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identifiant*", "Type*", "Titre*", "Nom auteur*", "Prénom", "Editeur*", "Annee", "Pages", "Langue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableOuvrage.setColumnSelectionAllowed(true);
        jTableOuvrage.setRowHeight(20);
        jTableOuvrage.setShowGrid(true);
        jTableOuvrage.getTableHeader().setReorderingAllowed(false);
        jScrollPaneOuvrage.setViewportView(jTableOuvrage);
        jTableOuvrage.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabelInfoMedia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInfoMedia.setText("Information médiathèque");

        jButtonAnnuler.setBackground(new java.awt.Color(255, 204, 204));
        jButtonAnnuler.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jScrollPaneMeta.setPreferredSize(new java.awt.Dimension(452, 202));

        jTableMeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Etat stock*", "Catégorie", "Univers", "Cote"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableMeta.setColumnSelectionAllowed(true);
        jScrollPaneMeta.setViewportView(jTableMeta);

        jLabelAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAjouter.setForeground(new java.awt.Color(0, 51, 255));
        jLabelAjouter.setText("Ajouter un ouvrage");

        jButtonEnvoyerAjout.setBackground(new java.awt.Color(153, 255, 153));
        jButtonEnvoyerAjout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEnvoyerAjout.setText("Envoyer");
        jButtonEnvoyerAjout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonEnvoyerAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvoyerAjoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMaJLayout = new javax.swing.GroupLayout(jPanelMaJ);
        jPanelMaJ.setLayout(jPanelMaJLayout);
        jPanelMaJLayout.setHorizontalGroup(
            jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaJLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jButtonSoumetAjout)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnvoyerAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAnnuler)
                .addGap(198, 198, 198))
            .addGroup(jPanelMaJLayout.createSequentialGroup()
                .addGroup(jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMaJLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabelTitreMaJ))
                    .addGroup(jPanelMaJLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneOuvrage, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInfoOuvrage)))
                    .addGroup(jPanelMaJLayout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabelAjouter)))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMaJLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addGroup(jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelInfoMedia)
                        .addGroup(jPanelMaJLayout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(jScrollPaneMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(435, Short.MAX_VALUE)))
        );
        jPanelMaJLayout.setVerticalGroup(
            jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaJLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreMaJ)
                .addGap(31, 31, 31)
                .addComponent(jLabelAjouter)
                .addGap(44, 44, 44)
                .addComponent(jLabelInfoOuvrage)
                .addGroup(jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMaJLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPaneOuvrage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 495, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMaJLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSoumetAjout)
                            .addComponent(jButtonEnvoyerAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAnnuler))
                        .addGap(141, 141, 141))))
            .addGroup(jPanelMaJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMaJLayout.createSequentialGroup()
                    .addGap(312, 312, 312)
                    .addComponent(jLabelInfoMedia)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPaneMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );

        bureau.add(jPanelMaJ, "card2");

        jLabelOuvrageSuppresion.setText("ouvrage à supprimer:");
        jLabelOuvrageSuppresion.setPreferredSize(new java.awt.Dimension(135, 29));

        jTextFieldSupression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupressionActionPerformed(evt);
            }
        });

        jLabelTitreSupression.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitreSupression.setText("Supression ouvrage");
        jLabelTitreSupression.setPreferredSize(new java.awt.Dimension(135, 14));
        jLabelTitreSupression.setRequestFocusEnabled(false);

        jButtonSuppression.setText("Rechercher");
        jButtonSuppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppressionActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jTableSupprimer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "id", "titre"
            }
        ));
        jScrollPane4.setViewportView(jTableSupprimer);

        javax.swing.GroupLayout jPanelSuppressionLayout = new javax.swing.GroupLayout(jPanelSuppression);
        jPanelSuppression.setLayout(jPanelSuppressionLayout);
        jPanelSuppressionLayout.setHorizontalGroup(
            jPanelSuppressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuppressionLayout.createSequentialGroup()
                .addGroup(jPanelSuppressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuppressionLayout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jButtonSupprimer))
                    .addGroup(jPanelSuppressionLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSuppressionLayout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabelTitreSupression, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSuppressionLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabelOuvrageSuppresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSupression, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSuppression)))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanelSuppressionLayout.setVerticalGroup(
            jPanelSuppressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuppressionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelTitreSupression, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(jPanelSuppressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOuvrageSuppresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSuppressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSuppression)
                        .addComponent(jTextFieldSupression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(135, 135, 135)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSupprimer)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        bureau.add(jPanelSuppression, "card6");

        jLabelTitreEmprunt.setText("Emprunts");

        jTableEmprunts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nom utilisateur", "Titre", "date emprunt", "date retour prevu", "adresse mail"
            }
        ));
        jScrollPaneEmpruntEnCours.setViewportView(jTableEmprunts);

        javax.swing.GroupLayout jPanelEmpruntLayout = new javax.swing.GroupLayout(jPanelEmprunt);
        jPanelEmprunt.setLayout(jPanelEmpruntLayout);
        jPanelEmpruntLayout.setHorizontalGroup(
            jPanelEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpruntLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabelTitreEmprunt)
                .addContainerGap(684, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpruntLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneEmpruntEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEmpruntLayout.setVerticalGroup(
            jPanelEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpruntLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelTitreEmprunt)
                .addGap(135, 135, 135)
                .addComponent(jScrollPaneEmpruntEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );

        bureau.add(jPanelEmprunt, "card7");

        contenant.add(bureau, java.awt.BorderLayout.CENTER);

        menuBar.setBackground(new java.awt.Color(0, 153, 153));
        menuBar.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N

        menuCatalogue.setForeground(new java.awt.Color(255, 255, 204));
        menuCatalogue.setText("Catalogue");
        menuCatalogue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuVoir.setBackground(new java.awt.Color(0, 153, 153));
        jMenuVoir.setForeground(new java.awt.Color(255, 255, 204));
        jMenuVoir.setText("Afficher");
        jMenuVoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVoirActionPerformed(evt);
            }
        });
        menuCatalogue.add(jMenuVoir);

        menuBar.add(menuCatalogue);

        menuRechercher.setForeground(new java.awt.Color(255, 255, 204));
        menuRechercher.setText("Rechercher");
        menuRechercher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuRecherche.setBackground(new java.awt.Color(0, 153, 153));
        jMenuRecherche.setForeground(new java.awt.Color(255, 255, 204));
        jMenuRecherche.setText("Rechercher");
        jMenuRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRechercheActionPerformed(evt);
            }
        });
        menuRechercher.add(jMenuRecherche);

        menuBar.add(menuRechercher);

        menuMaJ.setForeground(new java.awt.Color(255, 255, 204));
        menuMaJ.setText("Mise à Jour");
        menuMaJ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuAjout.setBackground(new java.awt.Color(0, 153, 153));
        jMenuAjout.setForeground(new java.awt.Color(255, 255, 204));
        jMenuAjout.setText("Ajouter");
        jMenuAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjoutActionPerformed(evt);
            }
        });
        menuMaJ.add(jMenuAjout);

        jMenuSuppression.setBackground(new java.awt.Color(0, 153, 153));
        jMenuSuppression.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSuppression.setText("Suppression");
        jMenuSuppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuppressionActionPerformed(evt);
            }
        });
        menuMaJ.add(jMenuSuppression);

        menuBar.add(menuMaJ);

        MenuEmprunt.setBackground(new java.awt.Color(0, 153, 153));
        MenuEmprunt.setForeground(new java.awt.Color(255, 255, 255));
        MenuEmprunt.setText("Emprunts");
        MenuEmprunt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuAfficheEmprunts.setBackground(new java.awt.Color(0, 153, 153));
        jMenuAfficheEmprunts.setForeground(new java.awt.Color(255, 255, 255));
        jMenuAfficheEmprunts.setText("Emprunts en cours");
        jMenuAfficheEmprunts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAfficheEmpruntsActionPerformed(evt);
            }
        });
        MenuEmprunt.add(jMenuAfficheEmprunts);

        menuBar.add(MenuEmprunt);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    /***************************************/
    /* Actions liées aux boutons du menu  */
    /*************************************/
    
    private void jMenuAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjoutActionPerformed
        jPanelAcceuil.setVisible(false);
        jPanelCatalogue.setVisible(false);
        jPanelRechercher.setVisible(false);
        jPanelMaJ.setVisible(true);
    }//GEN-LAST:event_jMenuAjoutActionPerformed

    private void jMenuVoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVoirActionPerformed
        this.app.afficherToutCatalogue();
        jPanelAcceuil.setVisible(false);
        jPanelCatalogue.setVisible(true);
        jPanelRechercher.setVisible(false);
        jPanelMaJ.setVisible(false);
    }//GEN-LAST:event_jMenuVoirActionPerformed

    private void jMenuRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRechercheActionPerformed
        jPanelAcceuil.setVisible(false);
        jPanelCatalogue.setVisible(false);
        jPanelRechercher.setVisible(true);
        jPanelMaJ.setVisible(false);
    }//GEN-LAST:event_jMenuRechercheActionPerformed

    /*********************************************************/
    /* Actions liées aux boutons du formulaire de recherche  */
    /********************************************************/
    
    private void jComboBoxTrouverChampsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrouverChampsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrouverChampsActionPerformed

    private void jButtonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercherActionPerformed
        jLabelRien.setVisible(false);
        this.app.rechercherDansCatalogue(this.getjComboBoxTrouverChamps().getSelectedIndex(), getjTextFieldRecherche().getText());
    }//GEN-LAST:event_jButtonRechercherActionPerformed

    /**************************************************/
    /* Actions liées aux boutons du formulaire d'ajout*/
    /*************************************************/
    
    private void jButtonSoumetAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoumetAjoutActionPerformed
        //Parcours du tableau pour récupérer les valeurs entrées dans le formulaire
        listeAttributsOuvrage = new ArrayList();
        for (int i = 0; i < this.jTableOuvrage.getColumnCount(); i++) {
            //vérifie s'il y a une valeur dans la case du tableau pour éviter plantage
            String valeurTableau = new String();
            if (this.jTableOuvrage.getValueAt(0, i) != null) {
                valeurTableau = this.jTableOuvrage.getValueAt(0, i).toString();
            }
            //Ajoute la valeur lue à la liste d'attributs de l'ouvrage
            listeAttributsOuvrage.add(valeurTableau);
        }

        for (int i = 0; i < this.jTableMeta.getColumnCount(); i++) {
            //vérifie s'il y a une valeur dans la case du tableau pour éviter plantage
            String valeurTableau = new String();
            if (this.jTableMeta.getValueAt(0, i) != null) {
                valeurTableau = this.jTableMeta.getValueAt(0, i).toString();
            }
            //Ajoute la valeur lue à la liste d'attributs de l'ouvrage
            listeAttributsOuvrage.add(valeurTableau);
        }

        //Appel de la fonction d'ajout
        this.app.validerOuvrage(listeAttributsOuvrage);
    }//GEN-LAST:event_jButtonSoumetAjoutActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        jPanelAcceuil.setVisible(true);
        jPanelMaJ.setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmerActionPerformed
        String createur = jComboBoxConfirmer.getSelectedItem().toString();
        idCreateur = parseInt(createur.substring(0,createur.indexOf(' ')));
        this.app.validerEditeur(listeAttributsOuvrage.get(4));
    }//GEN-LAST:event_jButtonConfirmerActionPerformed

    private void jButtonAjoutCreateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutCreateurActionPerformed
        //Parcours du tableau pour récupérer les valeurs entrées dans le formulaire
        ArrayList<String> listeAttributsCreateur = new ArrayList();
        for (int i = 0; i < this.jTableCreateur.getColumnCount(); i++) {
            //vérifie s'il y a une valeur dans la case du tableau pour éviter plantage
            String valeurTableau = new String();
            if (this.jTableCreateur.getValueAt(0, i) != null) {
                valeurTableau = this.jTableCreateur.getValueAt(0, i).toString();
            }
            //Ajoute la valeur lue à la liste d'attributs du créateur
            listeAttributsCreateur.add(valeurTableau);
        }
        idCreateur = this.app.ajouterCreateur(listeAttributsCreateur);
        this.app.validerEditeur(listeAttributsOuvrage.get(4));
    }//GEN-LAST:event_jButtonAjoutCreateurActionPerformed

    private void jButtonConfirmerEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmerEActionPerformed
        String editeur = jComboBoxConfirmerE.getSelectedItem().toString();
        idEditeur = parseInt(editeur.substring(0,editeur.indexOf(' ')));
        jDialogEditeur.setVisible(false);
        //confirmerOuvrage();
        this.app.ajouterOuvrage(listeAttributsOuvrage, idCreateur, idEditeur);
    }//GEN-LAST:event_jButtonConfirmerEActionPerformed

    private void jButtonAjoutEditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutEditeurActionPerformed
        //Parcours du tableau pour récupérer les valeurs entrées dans le formulaire
        ArrayList<String> listeAttributsEditeur = new ArrayList();
        for (int i = 0; i < this.jTableEditeur.getColumnCount(); i++) {
            //vérifie s'il y a une valeur dans la case du tableau pour éviter plantage
            String valeurTableau = new String();
            if (this.jTableEditeur.getValueAt(0, i) != null) {
                valeurTableau = this.jTableEditeur.getValueAt(0, i).toString();
            }
            //Ajoute la valeur lue à la liste d'attributs de l'ouvrage
            listeAttributsEditeur.add(valeurTableau);
        }
        idCreateur = this.app.ajouterEditeur(listeAttributsEditeur);
        jDialogEditeur.setVisible(false);
        //confirmerOuvrage();
        this.app.ajouterOuvrage(listeAttributsOuvrage, idCreateur, idEditeur);
    }//GEN-LAST:event_jButtonAjoutEditeurActionPerformed

    private void jButtonEnvoyerAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvoyerAjoutActionPerformed
        this.app.ajouterOuvrage(listeAttributsOuvrage, idCreateur, idEditeur);
    }//GEN-LAST:event_jButtonEnvoyerAjoutActionPerformed
/*action du bouton supprimer*/
    private void jMenuSuppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuppressionActionPerformed
 jPanelAcceuil.setVisible(false);
        jPanelCatalogue.setVisible(false);
        jPanelRechercher.setVisible(false);
        jPanelMaJ.setVisible(false);
        jPanelSuppression.setVisible(true);
    }//GEN-LAST:event_jMenuSuppressionActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
id= (String) this.jTableSupprimer.getValueAt(0,0);
titre = (String) this.jTableSupprimer.getValueAt(0,1);
        this.app.enleverOuvrage(id ,titre );
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jTextFieldSupressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupressionActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupressionActionPerformed

    private void jButtonSuppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppressionActionPerformed
         this.app.rechercherOuvrageSupression(this.getjComboBoxTrouverChamps().getSelectedIndex(), getjTextFieldSupression().getText());
    }//GEN-LAST:event_jButtonSuppressionActionPerformed

    private void jTextFieldRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRechercheActionPerformed

    private void jTableResAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableResAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableResAncestorAdded

    private void jMenuAfficheEmpruntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAfficheEmpruntsActionPerformed
     this.app.afficheEmprunt();
      jPanelAcceuil.setVisible(false);
        jPanelCatalogue.setVisible(false);
        jPanelRechercher.setVisible(false);
        jPanelMaJ.setVisible(false);
        jPanelSuppression.setVisible(false);
        jPanelEmprunt.setVisible(true);
     
    }//GEN-LAST:event_jMenuAfficheEmpruntsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuEmprunt;
    private javax.swing.JPanel bandeau;
    private javax.swing.JPanel bureau;
    private javax.swing.JPanel contenant;
    private javax.swing.JButton jButtonAjoutCreateur;
    private javax.swing.JButton jButtonAjoutEditeur;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonConfirmer;
    private javax.swing.JButton jButtonConfirmerE;
    private javax.swing.JButton jButtonEnvoyerAjout;
    private javax.swing.JButton jButtonRechercher;
    private javax.swing.JButton jButtonSoumetAjout;
    private javax.swing.JButton jButtonSuppression;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox<String> jComboBoxConfirmer;
    private javax.swing.JComboBox<String> jComboBoxConfirmerE;
    private javax.swing.JComboBox<String> jComboBoxTrouverChamps;
    private javax.swing.JDialog jDialogCreateur;
    private javax.swing.JDialog jDialogEditeur;
    private javax.swing.JLabel jLabeConfirmer;
    private javax.swing.JLabel jLabeConfirmerE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAjoutCreateur;
    private javax.swing.JLabel jLabelAjoutEditeur;
    private javax.swing.JLabel jLabelAjouter;
    private javax.swing.JLabel jLabelInfoMedia;
    private javax.swing.JLabel jLabelInfoOuvrage;
    private javax.swing.JLabel jLabelOuvrageSuppresion;
    private javax.swing.JLabel jLabelResultats;
    private javax.swing.JLabel jLabelRien;
    private javax.swing.JLabel jLabelTitreAcceuil;
    private javax.swing.JLabel jLabelTitreCatalogue;
    private javax.swing.JLabel jLabelTitreEmprunt;
    private javax.swing.JLabel jLabelTitreMaJ;
    private javax.swing.JLabel jLabelTitreRechercher;
    private javax.swing.JLabel jLabelTitreSupression;
    private javax.swing.JLabel jLabelTrouver;
    private javax.swing.JLabel jLabelTrouverDans;
    private javax.swing.JMenuItem jMenuAfficheEmprunts;
    private javax.swing.JMenuItem jMenuAjout;
    private javax.swing.JMenuItem jMenuRecherche;
    private javax.swing.JMenuItem jMenuSuppression;
    private javax.swing.JMenuItem jMenuVoir;
    private javax.swing.JPanel jPanelAcceuil;
    private javax.swing.JPanel jPanelCatalogue;
    private javax.swing.JPanel jPanelEmprunt;
    private javax.swing.JPanel jPanelMaJ;
    private javax.swing.JPanel jPanelRechercher;
    private javax.swing.JPanel jPanelSuppression;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPaneEmpruntEnCours;
    private javax.swing.JScrollPane jScrollPaneMeta;
    private javax.swing.JScrollPane jScrollPaneOuvrage;
    private javax.swing.JTable jTableCatalogue;
    private javax.swing.JTable jTableCreateur;
    private javax.swing.JTable jTableEditeur;
    private javax.swing.JTable jTableEmprunts;
    private javax.swing.JTable jTableMeta;
    private javax.swing.JTable jTableOuvrage;
    private javax.swing.JTable jTableRes;
    private javax.swing.JTable jTableSupprimer;
    private javax.swing.JTextField jTextFieldRecherche;
    private javax.swing.JTextField jTextFieldSupression;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCatalogue;
    private javax.swing.JMenu menuMaJ;
    private javax.swing.JMenu menuRechercher;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableCatalogue() {
        return jTableCatalogue;
    }

    public JComboBox<String> getjComboBoxTrouverChamps() {
        return jComboBoxTrouverChamps;
    }

    public JTextField getjTextFieldRecherche() {
        return jTextFieldRecherche;
    }

    public JTable getjTableRes() {
        return jTableRes;
    }

    public JLabel getjLabelRien() {
        return jLabelRien;
    }

    public int getIdCreateur() {
        return idCreateur;
    }
    
  
    public JTable getjTableEmprunts() {
        return jTableEmprunts;
    }
    
    public JTable getjTableSupprimer(){
        return jTableSupprimer;
    }
    
     public JTextField getjTextFieldSupression(){
        return jTextFieldSupression;
    }
    
   public String getId() {
        return id;
    }
    
    public String getTitre() {
        return titre;
    }
     
    /*
    * Affichage d'un message d'erreur
    */
    public void errorMessage(String texte) {
        JOptionPane.showMessageDialog(null, texte,"Error Message Box",JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * Affiche les informations du créateur dans le formulaire 
     * @param listeCreateurs
     * @param nomCreateur
     * @param prenomCreateur
     */
    public void proposerCreateur(ArrayList<Createur> listeCreateurs, String nomCreateur, String prenomCreateur) {
        //insère les créateurs possibles dans le menu déroulant
        if (!listeCreateurs.isEmpty()) {
            for (int i = 0; i < listeCreateurs.size(); i++) {
                String createur = listeCreateurs.get(i).getId() + " : "
                        + listeCreateurs.get(i).getType() + " , "
                        + listeCreateurs.get(i).getPrenom() + " "
                        + listeCreateurs.get(i).getNom() + ", " 
                        + listeCreateurs.get(i).getNaissance(); 
                this.jComboBoxConfirmer.addItem(createur);
           }
        }else {
            this.jComboBoxConfirmer.addItem("Aucun auteur de ce nom dans la base de données");
            this.jButtonConfirmer.setVisible(false);
       }
       
       //insère l'auteur de l'ouvrage à ajouter
       this.jTableCreateur.setValueAt(nomCreateur, 0, 0);
       this.jTableCreateur.setValueAt(prenomCreateur, 0, 1);
       
        //affiche la fenêtre de dialogue
        jDialogCreateur.setVisible(true);
    }
    
     /**
     * Affiche les informations du créateur dans le formulaire 
     * @param listeEditeurs
     * @param nomEditeur
     */
    public void proposerEditeur(ArrayList<Editeur> listeEditeurs, String nomEditeur) {
        //insère les éditeurs possibles dans le menu déroulant
        if (!listeEditeurs.isEmpty()) {
            for (int i = 0; i < listeEditeurs.size(); i++) {
                String editeur = listeEditeurs.get(i).getId() + " : "
                        + listeEditeurs.get(i).getType() + " , "
                        + listeEditeurs.get(i).getNom() + ", " 
                        + listeEditeurs.get(i).getVille(); 
                this.jComboBoxConfirmerE.addItem(editeur);
           }
        }else {
            this.jComboBoxConfirmerE.addItem("Aucun éditeur de ce nom dans la base de données");
            this.jButtonConfirmerE.setVisible(false);
       }
       
       //insère l'éditeur de l'ouvrage à ajouter
       this.jTableEditeur.setValueAt(nomEditeur, 0, 0);
       
       //affiche la fenêtre de dialogue
       jDialogEditeur.setVisible(true);
       jDialogCreateur.setVisible(false);
    }
    

    /**
     * Confirmation de l'ajout 
     */
    public void confirmerOuvrage() {
        jButtonEnvoyerAjout.setVisible(true);
        jButtonAnnuler.setVisible(true);
        jButtonSoumetAjout.setVisible(false);
    }
    
    
        public void closeAjouter() {
        jPanelAcceuil.setVisible(true);
        jPanelCatalogue.setVisible(false);
        jPanelRechercher.setVisible(false);
        jPanelMaJ.setVisible(false);
    }
    
    public void resetOuvrage() {
        DefaultTableModel model = (DefaultTableModel) jTableOuvrage.getModel();
        model.setRowCount(0);
        model.setRowCount(1);
        jTableOuvrage.setModel(model);
    }
}
    
    
